import { CASE_REVIEW_FACTS } from "./caseReview";
import { EDITOR_INITIAL, INITIAL_MESSAGES, renderedSourceMarkdown } from "./content";
import { validateReviewPayload } from "./review";
import type { AIReviewInput } from "./review";

export const INITIAL_REVIEW_INPUT: AIReviewInput = {
  facts: CASE_REVIEW_FACTS,
  messages: INITIAL_MESSAGES,
  briefMarkdown: renderedSourceMarkdown,
  reportMarkdown: EDITOR_INITIAL,
};

const supportedClaim = (
  claim: string,
  reportExcerpt: string,
  referenceId: string,
  rationale: string,
) => ({
  claim,
  reportExcerpt,
  referenceId,
  supportsClaim: true,
  rationale,
});

const unsupportedClaim = (
  claim: string,
  reportExcerpt: string,
  rationale: string,
) => ({
  claim,
  reportExcerpt,
  referenceId: null,
  supportsClaim: false,
  rationale,
});

const INITIAL_REVIEW_PAYLOAD = {
  coverage: [
    {
      factId: "current-reporting-failure",
      status: "elicited",
      rationale: "Sarah explained the WhatsApp workflow, buried messages, and day-long delays.",
      transcriptExcerpt: "messages get buried... Sometimes alerts go unnoticed for a whole day",
      chatMessageIndexes: [2],
      reportClaimIndexes: [0, 1, 13, 16],
    },
    {
      factId: "field-team-scale",
      status: "elicited",
      rationale: "The interview established both the field-worker count and district spread.",
      transcriptExcerpt: "about 40 field workers spread across three districts",
      chatMessageIndexes: [4],
      reportClaimIndexes: [8],
    },
    {
      factId: "case-manager-ownership",
      status: "elicited",
      rationale: "Sarah gave the case-manager count and described their responsibility.",
      transcriptExcerpt: "12 case managers - each case manager is responsible for a group of field workers",
      chatMessageIndexes: [4],
      reportClaimIndexes: [8],
    },
    {
      factId: "supervisor-oversight",
      status: "elicited",
      rationale: "Sarah identified the three supervisors and their high-severity role.",
      transcriptExcerpt: "3 supervisors who oversee everything and need to be looped in on high-severity incidents",
      chatMessageIndexes: [4],
      reportClaimIndexes: [],
    },
    {
      factId: "incident-volume",
      status: "elicited",
      rationale: "The busy-day incident volume was stated directly in the interview.",
      transcriptExcerpt: "On a busy day we might get 15 to 20 incident reports",
      chatMessageIndexes: [4],
      reportClaimIndexes: [],
    },
    {
      factId: "device-constraints",
      status: "assumed",
      rationale: "The report asserts the device constraint, but Sarah never stated it in the transcript.",
      reportExcerpt: "Field workers may have low-end Android devices",
      chatMessageIndexes: [],
      reportClaimIndexes: [9],
    },
    {
      factId: "connectivity-constraints",
      status: "assumed",
      rationale: "The report asserts intermittent connectivity without eliciting it from Sarah.",
      reportExcerpt: "intermittent connectivity",
      chatMessageIndexes: [],
      reportClaimIndexes: [9],
    },
    {
      factId: "notification-routing",
      status: "assumed",
      rationale: "The report includes submission and routing requirements that were not discussed in the transcript.",
      reportExcerpt: "Automatic notification to the assigned case manager and supervisor",
      chatMessageIndexes: [],
      reportClaimIndexes: [3, 4, 5, 11, 15],
    },
    {
      factId: "acknowledgement-escalation",
      status: "assumed",
      rationale: "Acknowledgement and escalation appear in the report but were not elicited from Sarah.",
      reportExcerpt: "Acknowledgement tracking with escalation when alerts are missed",
      chatMessageIndexes: [],
      reportClaimIndexes: [6],
    },
    {
      factId: "audit-and-reporting",
      status: "elicited",
      rationale: "Sarah described the lack of records and the resulting reporting difficulty.",
      transcriptExcerpt: "we have no proper records - just old chat messages",
      chatMessageIndexes: [2],
      reportClaimIndexes: [2, 7, 17, 18],
    },
  ],
  grounding: {
    claims: [
      supportedClaim(
        "The WhatsApp reporting flow is unreliable and hard to audit.",
        "BrightPath needs a replacement for WhatsApp group messages because the current reporting flow is unreliable and hard to audit.",
        "ref-0",
        "The attached case-brief reference supports the current-state problem.",
      ),
      supportedClaim(
        "Alerts can go unnoticed for a whole day.",
        "alerts can go unnoticed for a whole day",
        "ref-1",
        "The attached client reference states this directly.",
      ),
      supportedClaim(
        "The team has no proper records beyond old chat messages.",
        "no proper records - just old chat messages",
        "ref-2",
        "The attached client reference states this directly.",
      ),
      unsupportedClaim(
        "The desired outcome includes immediate notification and tracking every action.",
        "field workers can submit incidents, the right staff are notified immediately, and every action is tracked",
        "This factual requirement has no explicit source reference in its paragraph.",
      ),
      unsupportedClaim(
        "Incident submission must be mobile-friendly.",
        "Mobile-friendly incident submission for field workers",
        "This requirement has no explicit source reference.",
      ),
      unsupportedClaim(
        "The assigned case manager and supervisor must be notified automatically.",
        "Automatic notification to the assigned case manager and supervisor",
        "This requirement has no explicit source reference.",
      ),
      unsupportedClaim(
        "Missed alerts require acknowledgement tracking and escalation.",
        "Acknowledgement tracking with escalation when alerts are missed",
        "This requirement has no explicit source reference.",
      ),
      unsupportedClaim(
        "The system requires a persistent audit log of incidents and responses.",
        "Persistent audit log of incidents and responses",
        "This requirement has no explicit source reference.",
      ),
      supportedClaim(
        "The operation has about 40 field workers, three districts, and 12 case managers.",
        "about 40 field workers spread across three districts, and 12 case managers",
        "ref-3",
        "The attached client reference supplies the scale figures.",
      ),
      unsupportedClaim(
        "Field workers may have low-end Android devices and intermittent connectivity.",
        "Field workers may have low-end Android devices and intermittent connectivity",
        "The device and connectivity constraint has no explicit source reference.",
      ),
      supportedClaim(
        "The process should start simple and improve gradually.",
        "start simple, then gradually improve the design",
        "ref-4",
        "The attached case-brief reference supports this process constraint.",
      ),
      supportedClaim(
        "The system must immediately notify the assigned case manager and supervisor.",
        "the system immediately notifies the assigned case manager and supervisor",
        "ref-5",
        "The attached case-brief reference states this requirement.",
      ),
      supportedClaim(
        "Even one missed alert can have serious consequences for a child.",
        "even one missed alert can have serious consequences for a child",
        "ref-6",
        "The attached client reference states this directly.",
      ),
      supportedClaim(
        "BrightPath currently relies on unreliable WhatsApp group messages.",
        "unreliable WhatsApp group messages process",
        "ref-7",
        "The attached case-brief reference supports this description.",
      ),
      supportedClaim(
        "There is no way to know whether the right case manager saw or acted on an alert.",
        "there's no way to know if the right case manager actually saw it or is taking action",
        "ref-8",
        "The attached client reference states this directly.",
      ),
      supportedClaim(
        "The system should immediately notify the assigned case manager and supervisor.",
        "immediately notify the assigned case manager and supervisor",
        "ref-9",
        "The attached case-brief reference supports this requirement.",
      ),
      supportedClaim(
        "Alerts currently go unnoticed for a whole day.",
        "alerts go unnoticed for a whole day",
        "ref-10",
        "The attached client reference states this directly.",
      ),
      supportedClaim(
        "All incidents and responses must be stored for audit and reporting.",
        "all incidents and responses to be stored for audit and reporting",
        "ref-11",
        "The attached case-brief reference supports this requirement.",
      ),
      supportedClaim(
        "Current records consist only of old chat messages.",
        "no proper records - just old chat messages",
        "ref-12",
        "The attached client reference states this directly.",
      ),
    ],
    omissions: [
      {
        fact: "There are three supervisors overseeing the operation.",
        clientExcerpt: "there are 3 supervisors who oversee everything",
        messageIndex: 4,
        rationale: "The report mentions a supervisor role but omits the stated supervisor count.",
      },
      {
        fact: "A busy day produces 15 to 20 incident reports.",
        clientExcerpt: "On a busy day we might get 15 to 20 incident reports",
        messageIndex: 4,
        rationale: "The report does not carry the stated incident volume into the design context.",
      },
      {
        fact: "The WhatsApp group has too many participants.",
        clientExcerpt: "the group has too many people",
        messageIndex: 2,
        rationale: "The report describes buried messages but omits this contributing detail.",
      },
    ],
  },
  reasoning: [
    {
      kind: "assessment",
      statement: "Use an event-driven alert pipeline to fan out incidents while retaining an audit trail.",
      reportExcerpt: "An event-driven alert pipeline is a good fit here because one submitted incident needs to fan out to multiple recipients while keeping an audit trail.",
      section: "A - Assessment",
      rationale: "The design responds to the notification and audit requirements.",
      dependsOnClaimIndexes: [5, 7],
      dependsOnReasoningIndexes: [],
    },
    {
      kind: "assessment",
      statement: "Accept queue complexity in exchange for delivery reliability.",
      reportExcerpt: "A queue is worth the extra moving part because delivery reliability matters more than shaving off a small amount of latency.",
      section: "A - Assessment",
      rationale: "Missed-alert risk makes reliable delivery more important than minimal latency.",
      dependsOnClaimIndexes: [1, 12],
      dependsOnReasoningIndexes: [],
    },
    {
      kind: "plan",
      statement: "Define the incident submission API and payload.",
      reportExcerpt: "Define the incident submission API endpoint and payload schema",
      section: "P - Plan",
      rationale: "This operationalizes mobile incident submission.",
      dependsOnClaimIndexes: [4],
      dependsOnReasoningIndexes: [0],
    },
    {
      kind: "plan",
      statement: "Design the notification broadcast flow.",
      reportExcerpt: "Design the notification broadcast flow (Broadcast -> Queue -> Notification Server)",
      section: "P - Plan",
      rationale: "This operationalizes automatic notification routing.",
      dependsOnClaimIndexes: [5],
      dependsOnReasoningIndexes: [0, 1],
    },
    {
      kind: "plan",
      statement: "Store acknowledgements and escalation timestamps with each incident.",
      reportExcerpt: "Store acknowledgements and escalation timestamps alongside each incident",
      section: "P - Plan",
      rationale: "This implements escalation and auditability.",
      dependsOnClaimIndexes: [6, 7],
      dependsOnReasoningIndexes: [0, 1],
    },
    {
      kind: "plan",
      statement: "Confirm the delivery channels for the first release.",
      reportExcerpt: "Confirm delivery channels for the first release",
      section: "P - Plan",
      rationale: "The report identifies this as an unresolved implementation decision.",
      dependsOnClaimIndexes: [],
      dependsOnReasoningIndexes: [0],
    },
    {
      kind: "architecture",
      statement: "Route field submissions through an API Gateway.",
      reportExcerpt: "A[Field Worker App] --> B[API Gateway]",
      section: "System Design",
      rationale: "The architecture provides a single structured submission path.",
      dependsOnClaimIndexes: [4],
      dependsOnReasoningIndexes: [2],
    },
    {
      kind: "architecture",
      statement: "Persist incidents in the Incident DB.",
      reportExcerpt: "C --> D[(Incident DB)]",
      section: "System Design",
      rationale: "Persistent storage supports the audit-record requirement.",
      dependsOnClaimIndexes: [7],
      dependsOnReasoningIndexes: [4],
    },
    {
      kind: "architecture",
      statement: "Publish incident alerts through a queue to the notification service.",
      reportExcerpt: "C --> E[Alert Queue]",
      section: "System Design",
      rationale: "The queue separates incident intake from notification delivery.",
      dependsOnClaimIndexes: [5, 6],
      dependsOnReasoningIndexes: [3, 4],
    },
    {
      kind: "justification",
      statement: "Replace the WhatsApp workflow with a structured incident path.",
      reportExcerpt: "This flow directly replaces the unreliable [WhatsApp group messages]",
      section: "Design Justification",
      rationale: "The decision directly addresses the current reporting failure.",
      dependsOnClaimIndexes: [13],
      dependsOnReasoningIndexes: [6],
    },
    {
      kind: "justification",
      statement: "Use the gateway and incident server to establish one accountable intake route.",
      reportExcerpt: "The API Gateway and Incident Server give staff one clear way to log an incident",
      section: "Design Justification",
      rationale: "A clear intake route addresses uncertainty about receipt and action.",
      dependsOnClaimIndexes: [14],
      dependsOnReasoningIndexes: [6],
    },
    {
      kind: "justification",
      statement: "Use durable incident storage for acknowledgement and follow-up history.",
      reportExcerpt: "The Incident DB gives BrightPath a durable record of the incident, acknowledgement, and follow-up history",
      section: "Design Justification",
      rationale: "Durable storage supports audit and external reporting needs.",
      dependsOnClaimIndexes: [17, 18],
      dependsOnReasoningIndexes: [7],
    },
  ],
};

export const INITIAL_AI_REVIEW_RESULT = validateReviewPayload(
  INITIAL_REVIEW_PAYLOAD,
  INITIAL_REVIEW_INPUT,
);
